### ISSUE TITLE
iOS编译不过

### ISSUE THREAD

**Issue by shenhuniurou** [yubo725/rn-wechat#3]
报错信息：

** BUILD FAILED **

The following build commands failed:
	CompileC 
RNWeChat/ios/build/Build/Intermediates/imageCropPicker.build/Debug-iphonesimulator/imageCropPicker.build/Objects-normal/x86_64/ImageCropPicker-400F16F3CF62B860.o ImageCropPicker.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/TestReactNavigation.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/TestReactNavigation.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by yubo725** [comment]
iOS暂时还没适配，很多地方用的Android才有的组件，可以加QQ群一起讨论：419213248，群里有小伙伴已经在iOS上跑起来了，后面有机会我会适配iOS

**Comment by shenhuniurou** [comment]
@yubo725 好的
